### ISSUE TITLE
Fork of mpv-web-ui

### ISSUE THREAD

**Issue by open-dynaMIX** [makedin/mpv-web-ui#1]
Hi

I just wanted to inform you about my fork of mpv-web-ui. And even more thank you for the work you've done with it.
Prior to this I had almost no experience with Lua at all. Taking your code as a starting point made it easy for me to expand it's functionality.

You can find the repository [here](/open-dynaMIX/simple-mpv-webui).

Best regards

**Comment by makedin** [comment]
Thanks for letting me know! It seems you have taken the project (I wrote the original version one night for an immediate need) to a completely new level. Maybe this way it will prove useful for more people.
